name: Monitor de stock

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Ejecutar monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python monitor.py
